<?php
/**
 * LeadProof - Report Generator Service
 * Generates HTML & PDF data quality reports
 */

declare(strict_types=1);

namespace App\Services;

use Dompdf\Dompdf;
use Dompdf\Options;

class ReportGeneratorService
{
    private string $storagePath;

    public function __construct()
    {
        $this->storagePath = dirname(__DIR__, 2) . '/storage/reports';

        if (!is_dir($this->storagePath)) {
            mkdir($this->storagePath, 0775, true);
        }
    }

    /**
     * Generate PDF report
     */
    public function generate(
        array $stats,
        array $crmValidation,
        string $fileName = 'leadproof_report'
    ): string {
        $html = $this->buildHtml($stats, $crmValidation);

        $options = new Options();
        $options->set('defaultFont', 'DejaVu Sans');

        $dompdf = new Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();

        $filePath = $this->storagePath . '/' . $fileName . '_' . time() . '.pdf';
        file_put_contents($filePath, $dompdf->output());

        return $filePath;
    }

    /**
     * Build report HTML
     */
    private function buildHtml(array $stats, array $crm): string
    {
        $score = $stats['crm_readiness']['score'] ?? 0;
        $level = strtoupper($stats['crm_readiness']['level'] ?? 'UNKNOWN');

        $recommendation = $crm['import_recommendation'] ?? 'review';

        return "
        <html>
        <head>
            <style>
                body { font-family: DejaVu Sans; font-size: 12px; }
                h1 { color: #111; }
                h2 { margin-top: 30px; }
                table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background-color: #f5f5f5; }
                .badge {
                    display: inline-block;
                    padding: 6px 10px;
                    font-weight: bold;
                    border-radius: 4px;
                }
                .safe { background: #d4edda; }
                .review { background: #fff3cd; }
                .risky { background: #f8d7da; }
            </style>
        </head>
        <body>

            <h1>LeadProof – Data Quality Report</h1>

            <p><strong>CRM:</strong> " . strtoupper($crm['crm']) . "</p>

            <h2>CRM Readiness</h2>
            <p>
                <span class='badge {$stats['crm_readiness']['level']}'>
                    Score: {$score} / 100 ({$level})
                </span>
            </p>

            <h2>Row Summary</h2>
            <table>
                <tr><th>Total Rows</th><td>{$stats['rows']['total']}</td></tr>
                <tr><th>Valid Rows</th><td>{$stats['rows']['valid']}</td></tr>
                <tr><th>Excluded Rows</th><td>{$stats['rows']['excluded']}</td></tr>
            </table>

            <h2>Detected Issues</h2>
            <table>
                <tr><th>Duplicate Emails</th><td>{$stats['issues']['duplicates']}</td></tr>
                <tr><th>Invalid Emails</th><td>{$stats['issues']['invalid_emails']}</td></tr>
                <tr><th>Duplicate Rate (%)</th><td>{$stats['rates']['duplicate_rate']}</td></tr>
                <tr><th>Invalid Email Rate (%)</th><td>{$stats['rates']['invalid_email_rate']}</td></tr>
            </table>

            <h2>Field Completeness</h2>
            <table>
        ";

        foreach ($stats['completeness']['details'] as $field => $value) {
            $html .= "<tr><th>{$field}</th><td>{$value}%</td></tr>";
        }

        $html .= "
            </table>

            <h2>CRM Import Recommendation</h2>
            <p><strong>{$this->formatRecommendation($recommendation)}</strong></p>

            <h2>Warnings</h2>
            <ul>
        ";

        foreach ($crm['warnings'] as $warning) {
            $html .= "<li>{$warning}</li>";
        }

        $html .= "
            </ul>

            <hr>
            <p><em>Generated by LeadProof</em></p>

        </body>
        </html>
        ";

        return $html;
    }

    /**
     * Format recommendation text
     */
    private function formatRecommendation(string $key): string
    {
        return match ($key) {
            'safe_to_import' => 'Safe to Import',
            'review_before_import' => 'Review Before Import',
            'do_not_import' => 'Do Not Import',
            default => 'Review Required',
        };
    }
}
